### ISSUE TITLE
`istio-gateway` charm does not expose an option for internal LB when deploying on EKS

### ISSUE THREAD

**Issue by gustavosr98** [canonical/istio-operators#345]
### Bug Description

Deploying istio gateway as a LoadBalancer on AWS EKS will by default create an AWS Load Balancer that is exposed to the Internet by default

There are multiple cases where because of security constraints this needs to be only exposed to internal networks and not to the Internet.
This also applies when deploying a private EKS that is only available on private VPCs and not publicly available VPCs.

I would like to have exposed the option to add the required annotation on the charm to deploy the LoadBalancer as a internal LoadBalancer rather than a private one

See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-internal

### To Reproduce

juju deploy --trust --debug istio-gateway \
--channel=1.16/stable \
--config kind=ingress \
--config gateway_service_type=LoadBalancer

### Environment

AWS EKS
Juju 2.9.45
Charm channel: 1.16/stable
Charm revision: 663

### Relevant log output

```shell
n/a
```

### Additional context

Some additional external reference
https://anshul-prakash17.medium.com/creating-an-internal-load-balancer-in-aws-eks-using-istio-3defcb51c6a2

**Workaround**
1. Create the service as a NodePort initially, so the LoadBalancer doesn't get created on AWS
```bash
juju deploy --trust --debug istio-gateway \
--channel=1.16/stable \
--config kind=ingress \
--config gateway_service_type=NodePort
```

2. Edit the [manifest.yaml located on the charm source code](https://github.com/canonical/istio-operators/blob/main/charms/istio-gateway/src/manifest.yaml) to add the service annotation for internal lb
```yaml
# [..]
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: istio-{{ kind }}gateway
    install.operator.istio.io/owning-resource: unknown
    istio: {{ kind }}gateway
    istio.io/rev: default
    operator.istio.io/component: "{{ kind|capitalize }}Gateways"
    release: istio
  name: istio-{{ kind }}gateway-workload
  namespace: {{ namespace }}
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    istio: {{ kind }}gateway
  type: {{ 'ClusterIP' if kind == 'egress' else gateway_service_type }}
```
  
3. Push the new manifest.yaml into the deployed charm
```bash
juju scp new-manifest.yaml istio-gateway/0:/var/lib/juju/agents/unit-istio-gateway-0/charm/src/manifest.yaml
```
  
4. Change the service type to LoadBalancer
```bash
juju config istio-gateway gateway_service_type=LoadBalancer
```
