### ISSUE TITLE
Test `ISVC` in a service mesh with Istio CNI plugin installed

### ISSUE THREAD

**Issue by DnPlas** [canonical/istio-operators#354]
### What needs to get done

Because of the Istio CNI plugin [limitations](https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers), the Kserve InferenceServices (`ISVC`) may be affected by the network configuration, as each `ISVC` has a `storage-initializer` init-container, which executes [this code](https://github.com/kserve/kserve/blob/master/python/storage-initializer/scripts/initializer-entrypoint#L15C1-L15C37), which may require network connectivity.

NOTE: this scenario is possible for other workloads, not just ISVCs, so the documentation should be generic enough to cover all.

This task requires us to create a Kserve InferenceService inside an Istio mesh with the Istio CNI plugin enabled. Since it will most likely produce an error, we need to provide a solution and document that solution.

DOD:

* Documentation with a workaround for the issue

### Why it needs to get done

To avoid potential issues when we enable the Istio CNI plugin.

**Comment by DnPlas** [comment]
This issue can be workaround by adding the right annotations to the `Pod` that eventually gets created via the `InferenceService` definition. Something like this should help:

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-workaround"
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: "0.0.0.0/0"
spec:
...
```

This workaround is provided in the [official documentation](https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers) and has also been tested in upstream https://github.com/kubeflow/manifests/issues/2014#issuecomment-1036168983.

Please note this is a workaround and a real solution should be something that applies to any workload, this effort will be tracked in #356
