### ISSUE TITLE
Manage Istio ExtensionProvider's via charm

### ISSUE THREAD

**Issue by valexby** [canonical/istio-operators#393]
### Context

There is currently no manageable way to configure [Istio enable ExtensionProvider](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider)'s. The useful business application of it is to enable [the Istio External Authorization](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/) for the charmed istio.
Currently, the only way to enable External Auth is to manually update `istio` configmap, but charm becomes unable to manage `istio` after that.

### What needs to get done

1. `istio` configmap seems to be generated by some of the `istio` charms, I suppose by `istio-ingressgateway`. 
2. Add configuration key `extension_providers` to the `istio-ingressgateway` charm. This config key should accept `yaml` and charm should install the value into `istio` configmap into `.data.mesh.extensionProviders` array. 

### Definition of Done

1. update configuration of extensionProviders like
```
juju config istio-ingressgateway extension_providers="""
extensionProviders:
- name: "ext-authz-http-prd"
  envoyExtAuthzHttp:
    service: <>.svc.cluster.local
    port: 9700
    includeRequestHeadersInCheck: ["jwt-claim"]
    includeRequestBodyInCheck:
      maxRequestBytes: 2048
      allowPartialMessage: true
- name: "ext-authz-grpc-prd"
  envoyExtAuthzGrpc:
    service: <>.svc.cluster.local
    port: 9090
    includeRequestBodyInCheck:
      maxRequestBytes: 2048
      packAsBytes: true
      allowPartialMessage: true
"""
```
2. After charm is settled, `istio` config map get the value provided above populated into `.data.mesh.extensionProviders`.
